# Project P3: Cooperation and Competition &mdash; Environment

In [1]:
from utils import Config, MyEncoder

import numpy as np
import types

In [2]:
config = Config()
config.fc1_units = 128
config.fc2_units = 64
config.gamma = 0.96
config.max_t = int(2e3)

config.n_learn_steps = 10
config.n_learn_updates = 5

print(config.to_dict())

Path results already exists


INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


{'n_agents': 2, 'target_episode': None, 'target_score': None, 'device': device(type='cpu'), 'model_id_auto': True, 'model_id': 66, 'env_path': PosixPath('Tennis.x86_64'), 'brain_name': 'TennisBrain', 'state_dim': 24, 'action_dim': 2, 'n_episodes': 5000, 'max_t': 2000, 'buffer_size': 1000000, 'batch_size': 128, 'gamma': 0.96, 'tau': 0.06, 'lr_actor': 0.001, 'lr_critic': 0.001, 'critic_weight_decay': 0, 'fc1_units': 128, 'fc2_units': 64, 'seed': 48, 'n_print': 100, 'target': 0.5, 'window': 100, 'n_learn_steps': 10, 'n_learn_updates': 5, 'all_episodes': True}


## Brain

In [3]:
items = [d for d in dir(config.env) if not d.startswith('_')]

items

['academy_name',
 'brain_names',
 'brains',
 'close',
 'communicator',
 'curriculum',
 'executable_launcher',
 'external_brain_names',
 'get_communicator',
 'global_done',
 'logfile_path',
 'number_brains',
 'number_external_brains',
 'port',
 'proc1',
 'reset',
 'send_academy_parameters',
 'step',
 'wrap_unity_input']

In [4]:
print(f"Attributes:\n{'-'*len('Attributes')}")
for item in items:
    attr = getattr(config.env, item)

    if isinstance(attr, int) and not isinstance(attr, bool):
        print(f'{item} is an integer:\n  ', attr)
    if isinstance(attr, list):
        print(f'{item} is a list of length {len(attr)}:\n  ', attr)
    elif isinstance(attr, np.ndarray):
        print(f'{item} is a np.ndarray of shape {attr.shape}:\n  ', attr)
    elif isinstance(attr, str):
        print(f'{item} is a string of length {len(attr)}:\n  ', attr)
    elif isinstance(attr, dict):
        print(f'{item} is a dict with {len(attr.keys())} keys:\n  ', attr)
    elif isinstance(attr, bool):
        print(f'{item} is a boolean:\n  ', attr)
    else:
        pass

print(f"\nClasses:\n{'-'*len('Classes')}")
for item in items:
    attr = getattr(config.env, item)

    if hasattr(attr, '__class__') and not isinstance(attr, (int, str, list, dict, bool, types.MethodType)):
        print(f'{item}')
    else:
        pass    
    
print(f"\nMethods:\n{'-'*len('Methods')}")
for item in items:
    attr = getattr(config.env, item)

    if isinstance(attr, types.MethodType):
        print(f'{item}')
    else:
        pass

Attributes:
----------
academy_name is a string of length 7:
   Academy
brain_names is a list of length 1:
   ['TennisBrain']
brains is a dict with 1 keys:
   {'TennisBrain': <unityagents.brain.BrainParameters object at 0x7f57a3b24ac8>}
external_brain_names is a list of length 1:
   ['TennisBrain']
global_done is a boolean:
   False
logfile_path is a string of length 0:
   
number_brains is an integer:
   1
number_external_brains is an integer:
   1
port is an integer:
   5005

Classes:
-------
communicator
curriculum
proc1

Methods:
-------
close
executable_launcher
get_communicator
reset
send_academy_parameters
step
wrap_unity_input


## Env Info

In [5]:
env_info = config.env.reset(train_mode=True)[config.brain_name]

items = [d for d in dir(env_info) if not d.startswith('_')]

items

['agents',
 'local_done',
 'max_reached',
 'memories',
 'previous_text_actions',
 'previous_vector_actions',
 'rewards',
 'text_observations',
 'vector_observations',
 'visual_observations']

In [6]:
for item in items:
    attr = getattr(env_info, item)

    if isinstance(attr, list):
        print(f'{item} is a list of length {len(attr)}:\n  ', attr)
    elif isinstance(attr, np.ndarray):
        print(f'{item} is a np.ndarray of shape {attr.shape}:\n  ', attr)
    else:
        print(f'{item} is a {type(attr)}:\n  ', attr)


agents is a list of length 2:
   [942, 952]
local_done is a list of length 2:
   [False, False]
max_reached is a list of length 2:
   [False, False]
memories is a np.ndarray of shape (0, 0):
   []
previous_text_actions is a list of length 2:
   ['', '']
previous_vector_actions is a np.ndarray of shape (2, 2):
   [[0. 0.]
 [0. 0.]]
rewards is a list of length 2:
   [0.0, 0.0]
text_observations is a list of length 2:
   ['', '']
vector_observations is a np.ndarray of shape (2, 24):
   [[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.         -7.38993645 -1.5
  -0.          0.          6.83172083  5.99607611 -0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.         -6.70024681 -1.5
   0.          0.         -6.83172083  

## Action Space

In [7]:
actions = np.random.randn(config.n_agents, config.action_dim)

actions, type(actions), actions.shape

(array([[ 0.08434264,  0.25171786],
        [ 0.97517201, -1.3804798 ]]), numpy.ndarray, (2, 2))

## Observation Space

In [8]:
states = env_info.vector_observations

states, type(states), states.shape

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        , -7.38993645, -1.5       , -0.        ,  0.        ,
          6.83172083,  5.99607611, -0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        , -6.70024681, -1.5       ,  0.        ,  0.        ,
         -6.83172083,  5.99607611,  0.        ,  0.        ]]),
 numpy.ndarray,
 (2, 24))

## Random Actions

In [9]:
n_episodes = 5  # play the game for n episodes

for i_episode in range(1, n_episodes + 1):
    env_info = config.env.reset(train_mode=True)[config.brain_name]

    states = env_info.vector_observations
    print(f'States is a {type(states)} of shape {states.shape}\n', states)
    
    score = np.zeros(config.n_agents)
    print(f'Scores is a {type(score)} of shape {score.shape}\n', score)
    
    max_t = 0

    for t in range(config.max_t):
        max_t = t
        
        actions = np.random.randn(config.n_agents, config.action_dim)
        print(f'Actions is a {type(actions)} of shape {actions.shape}\n', actions)

        env_info = config.env.step(actions)[config.brain_name]

        next_states = env_info.vector_observations
        print(f'Next States is a {type(next_states)} of shape {next_states.shape}\n', next_states)

        rewards = env_info.rewards
        print(f'Rewards is a {type(rewards)} of length {len(rewards)}\n', rewards)

        dones = env_info.local_done
        print(f'Dones is a {type(dones)} of length {len(dones)}\n', dones)


        states = next_states

        score += rewards
        print(f'Score is a {type(score)} of shape {score.shape}\n', score)

        if np.any(dones):
            max_t = t
            break

    print(f'Max score over both agents for episode {i_episode} is {np.max(score)} in {max_t} timesteps')
        
config.env.close()

States is a <class 'numpy.ndarray'> of shape (2, 24)
 [[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.         -6.69487906 -1.5
  -0.          0.          6.83172083  5.98822832 -0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.         -6.99633169 -1.5
   0.          0.         -6.83172083  5.98822832  0.          0.        ]]
Scores is a <class 'numpy.ndarray'> of shape (2,)
 [0. 0.]
Actions is a <class 'numpy.ndarray'> of shape (2, 2)
 [[-0.84600129  0.32239179]
 [ 0.11899566  0.56222142]]
Next States is a <class 'numpy.ndarray'> of shape (2, 24)
 [[  0.           0.           0.           0.           0.
    0.           0.           0.          -6.69487906  -1.5
   -0.           0.           6.83172083   5.988228

Next States is a <class 'numpy.ndarray'> of shape (2, 24)
 [[ -0.39999998   0.55696607  30.           2.48740244   6.83172083
    0.65461326  30.           2.48740244  -0.72788435   0.74684626
   13.6057806    1.50640261   6.83172083  -0.26500678  13.6057806
    1.50640261  -0.62377769   0.8386265   18.81111145   0.52540255
    5.90394354  -1.18248439  18.81111145   0.52540255]
 [-10.90239716   0.54917783   0.          -2.61379719  -6.83172083
    0.65461326   0.          -2.61379719  -7.90239477   0.22893813
   30.          -3.59479666  -6.83172083  -0.26500678  30.
   -3.59479666  -7.33001947  -0.19141001   6.11333036  -4.59588099
   -5.90394354  -1.18248439   6.11333036  -4.59588099]]
Rewards is a <class 'list'> of length 2
 [0.0, 0.0]
Dones is a <class 'list'> of length 2
 [False, False]
Score is a <class 'numpy.ndarray'> of shape (2,)
 [0. 0.]
Actions is a <class 'numpy.ndarray'> of shape (2, 2)
 [[-1.44778186 -0.16882692]
 [ 0.3157161  -1.53357308]]
Next States is a <class 'numpy

   -6.37251186   3.52788067   0.           1.3102026 ]]
Rewards is a <class 'list'> of length 2
 [0.0, 0.0]
Dones is a <class 'list'> of length 2
 [False, False]
Score is a <class 'numpy.ndarray'> of shape (2,)
 [0. 0.]
Actions is a <class 'numpy.ndarray'> of shape (2, 2)
 [[ 0.97597826  0.01602197]
 [ 0.02796478 -0.15450653]]
Next States is a <class 'numpy.ndarray'> of shape (2, 24)
 [[ -1.31839824  -1.85216224  30.           0.           6.37251186
    4.17534065  30.           0.          -3.41582131  -1.18355429
  -20.97423553   6.41140032   6.37251186   3.52788067 -20.97423553
    6.41140032  -0.48788619  -0.60127413  29.27934837   5.43040085
    6.37251186   2.78232098  29.27934837   5.43040085]
 [-10.91825962   0.67887664   0.           2.29120255  -6.37251186
    4.17534065   0.           2.29120255 -10.89979553   0.84913683
    0.           1.3102026   -6.37251186   3.52788067   0.
    1.3102026  -10.8159008    0.92129707   0.8389433    0.32920253
   -6.37251186   2.78232098  